model:
  name: DeepDeblur
  n_channels: 64

training:
  learning_rate: 0.00005
  patience: 5
  epochs: 600
  batch_size: 2
  start_epoch: 1
  save_every: 3
  per_channel_mean: 0.5
  reduce_lr_after: 200
  gamma: 0.1


checkpoint:
  continue: false
  id: "2025-03-26_06-16-57"
  type: best