use_debugger: true

environment:
  kaggle: true
  dataset_base:
    kaggle: "/kaggle/input/a-curated-list-of-image-deblurring-datasets/DBlur/Gopro"
    local: "/home/mahmoud-sayed/Desktop/Datasets/Gopro Dataset"
  output_dir:
    kaggle: "output"
    local: "output"
  debugger_active: true

device: cuda